[package]
name = "otp"
version = "0.1.0"
description = "Implementation of the One-Time Pad cipher"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8.5"
